In [2]:
import yfinance as yf
import pandas as py

In [3]:
tickers=["AAPL","MSFT","NVDA","GOOGL","AMZN"]
prices=yf.download(tickers,start="2021-01-01",end="2026-01-01",auto_adjust=True)
prices.head()

[*********************100%***********************]  5 of 5 completed

Price            Close                                                \
Ticker            AAPL        AMZN      GOOGL        MSFT       NVDA
Date
2021-01-04  125.632507  159.331497  85.492981  207.565384  13.046198
2021-01-05  127.185738  160.925507  86.182419  207.765640  13.335952
2021-01-06  122.904510  156.919006  85.332008  202.378372  12.549760
2021-01-07  127.098419  158.108002  87.880753  208.137482  13.275517
2021-01-08  128.195419  159.134995  89.044174  209.405594  13.208611

Price             High                                                ...  \
Ticker            AAPL        AMZN      GOOGL        MSFT       NVDA  ...
Date                                                                  ...
2021-01-04  129.709906  163.600006  87.293838  212.628417  13.582432  ...
2021-01-05  127.894439  161.169006  86.518220  208.356814  13.374503  ...
2021-01-06  127.224618  159.875504  86.376573  206.421177  13.177024  ...
2021-01-07  127.787701  160.427002  88.053108  209.138650  13.309094  ...
2021-01-08  128.758491  159.531998  89.119953  210.320951  13.352120  ...

Price             Open                                                \
Ticker            AAPL        AMZN      GOOGL        MSFT       NVDA
Date
2021-01-04  129.622536  163.500000  87.170515  212.180275  13.036996
2021-01-05  125.127626  158.300507  85.441468  207.155407  13.032517
2021-01-06  123.991820  157.324005  84.211672  202.302091  13.154639
2021-01-07  124.613148  157.850006  85.524172  204.085146  12.900949
2021-01-08  128.564317  159.000000  88.020415  208.509310  13.293921

Price          Volume
Ticker           AAPL      AMZN     GOOGL      MSFT       NVDA
Date
2021-01-04  143301900  88228000  37324000  37130100  560640000
2021-01-05   97664900  53110000  20360000  23823000  322760000
2021-01-06  155088000  87896000  46588000  35930700  580424000
2021-01-07  109578200  70290000  41936000  27694500  461480000
2021-01-08  105158200  70754000  35484000  22956200  292528000

[5 rows x 25 columns]

In [4]:
close=prices["Close"]
print(close.head())

Ticker            AAPL        AMZN      GOOGL        MSFT       NVDA
Date
2021-01-04  125.632507  159.331497  85.492981  207.565384  13.046198
2021-01-05  127.185738  160.925507  86.182419  207.765640  13.335952
2021-01-06  122.904510  156.919006  85.332008  202.378372  12.549760
2021-01-07  127.098419  158.108002  87.880753  208.137482  13.275517
2021-01-08  128.195419  159.134995  89.044174  209.405594  13.208611

In [5]:
returns=close.pct_change().dropna()
returns.head()

Ticker          AAPL      AMZN     GOOGL      MSFT      NVDA
Date
2021-01-05  0.012363  0.010004  0.008064  0.000965  0.022210
2021-01-06 -0.033661 -0.024897 -0.009868 -0.025930 -0.058953
2021-01-07  0.034123  0.007577  0.029869  0.028457  0.057830
2021-01-08  0.008631  0.006496  0.013239  0.006093 -0.005040
2021-01-11 -0.023249 -0.021519 -0.023105 -0.009699  0.025966

In [6]:
cov_daily=returns.cov()

In [7]:
cov_annual=cov_daily*252